// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arithmetic_service.proto

#include "arithmetic_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Arithmetic {
class ReqOperandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqOperand>
      _instance;
} _ReqOperand_default_instance_;
class RspOperandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RspOperand>
      _instance;
} _RspOperand_default_instance_;
}  // namespace Arithmetic
namespace protobuf_arithmetic_5fservice_2eproto {
static void InitDefaultsReqOperand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arithmetic::_ReqOperand_default_instance_;
    new (ptr) ::Arithmetic::ReqOperand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Arithmetic::ReqOperand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqOperand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqOperand}, {}};

static void InitDefaultsRspOperand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arithmetic::_RspOperand_default_instance_;
    new (ptr) ::Arithmetic::RspOperand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Arithmetic::RspOperand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RspOperand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRspOperand}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqOperand.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RspOperand.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmetic::ReqOperand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmetic::ReqOperand, num_1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmetic::ReqOperand, num_2_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmetic::RspOperand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Arithmetic::RspOperand, num_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Arithmetic::ReqOperand)},
  { 7, -1, sizeof(::Arithmetic::RspOperand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Arithmetic::_ReqOperand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Arithmetic::_RspOperand_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "arithmetic_service.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030arithmetic_service.proto\022\nArithmetic\"*"
      "\n\nReqOperand\022\r\n\005num_1\030\001 \001(\005\022\r\n\005num_2\030\002 \001"
      "(\005\"\031\n\nRspOperand\022\013\n\003num\030\001 \001(\0052\203\001\n\tInterf"
      "ace\022:\n\006GetSum\022\026.Arithmetic.ReqOperand\032\026."
      "Arithmetic.RspOperand\"\000\022:\n\006GetSub\022\026.Arit"
      "hmetic.ReqOperand\032\026.Arithmetic.RspOperan"
      "d\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 251);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "arithmetic_service.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_arithmetic_5fservice_2eproto
namespace Arithmetic {

// ===================================================================

void ReqOperand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqOperand::kNum1FieldNumber;
const int ReqOperand::kNum2FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqOperand::ReqOperand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_arithmetic_5fservice_2eproto::scc_info_ReqOperand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Arithmetic.ReqOperand)
}
ReqOperand::ReqOperand(const ReqOperand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&num_1_, &from.num_1_,
    static_cast<size_t>(reinterpret_cast<char*>(&num_2_) -
    reinterpret_cast<char*>(&num_1_)) + sizeof(num_2_));
  // @@protoc_insertion_point(copy_constructor:Arithmetic.ReqOperand)
}

void ReqOperand::SharedCtor() {
  ::memset(&num_1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_2_) -
      reinterpret_cast<char*>(&num_1_)) + sizeof(num_2_));
}

ReqOperand::~ReqOperand() {
  // @@protoc_insertion_point(destructor:Arithmetic.ReqOperand)
  SharedDtor();
}

void ReqOperand::SharedDtor() {
}

void ReqOperand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqOperand::descriptor() {
  ::protobuf_arithmetic_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmetic_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqOperand& ReqOperand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_arithmetic_5fservice_2eproto::scc_info_ReqOperand.base);
  return *internal_default_instance();
}


void ReqOperand::Clear() {
// @@protoc_insertion_point(message_clear_start:Arithmetic.ReqOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&num_1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_2_) -
      reinterpret_cast<char*>(&num_1_)) + sizeof(num_2_));
  _internal_metadata_.Clear();
}

bool ReqOperand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Arithmetic.ReqOperand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num_1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 num_2 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Arithmetic.ReqOperand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Arithmetic.ReqOperand)
  return false;
#undef DO_
}

void ReqOperand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Arithmetic.ReqOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_1 = 1;
  if (this->num_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_1(), output);
  }

  // int32 num_2 = 2;
  if (this->num_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->num_2(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Arithmetic.ReqOperand)
}

::google::protobuf::uint8* ReqOperand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Arithmetic.ReqOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_1 = 1;
  if (this->num_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_1(), target);
  }

  // int32 num_2 = 2;
  if (this->num_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->num_2(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arithmetic.ReqOperand)
  return target;
}

size_t ReqOperand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arithmetic.ReqOperand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 num_1 = 1;
  if (this->num_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_1());
  }

  // int32 num_2 = 2;
  if (this->num_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqOperand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arithmetic.ReqOperand)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqOperand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqOperand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arithmetic.ReqOperand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arithmetic.ReqOperand)
    MergeFrom(*source);
  }
}

void ReqOperand::MergeFrom(const ReqOperand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arithmetic.ReqOperand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num_1() != 0) {
    set_num_1(from.num_1());
  }
  if (from.num_2() != 0) {
    set_num_2(from.num_2());
  }
}

void ReqOperand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arithmetic.ReqOperand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqOperand::CopyFrom(const ReqOperand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arithmetic.ReqOperand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqOperand::IsInitialized() const {
  return true;
}

void ReqOperand::Swap(ReqOperand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqOperand::InternalSwap(ReqOperand* other) {
  using std::swap;
  swap(num_1_, other->num_1_);
  swap(num_2_, other->num_2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqOperand::GetMetadata() const {
  protobuf_arithmetic_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmetic_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RspOperand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RspOperand::kNumFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RspOperand::RspOperand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_arithmetic_5fservice_2eproto::scc_info_RspOperand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Arithmetic.RspOperand)
}
RspOperand::RspOperand(const RspOperand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  num_ = from.num_;
  // @@protoc_insertion_point(copy_constructor:Arithmetic.RspOperand)
}

void RspOperand::SharedCtor() {
  num_ = 0;
}

RspOperand::~RspOperand() {
  // @@protoc_insertion_point(destructor:Arithmetic.RspOperand)
  SharedDtor();
}

void RspOperand::SharedDtor() {
}

void RspOperand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RspOperand::descriptor() {
  ::protobuf_arithmetic_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmetic_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RspOperand& RspOperand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_arithmetic_5fservice_2eproto::scc_info_RspOperand.base);
  return *internal_default_instance();
}


void RspOperand::Clear() {
// @@protoc_insertion_point(message_clear_start:Arithmetic.RspOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  num_ = 0;
  _internal_metadata_.Clear();
}

bool RspOperand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Arithmetic.RspOperand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Arithmetic.RspOperand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Arithmetic.RspOperand)
  return false;
#undef DO_
}

void RspOperand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Arithmetic.RspOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Arithmetic.RspOperand)
}

::google::protobuf::uint8* RspOperand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Arithmetic.RspOperand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num = 1;
  if (this->num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arithmetic.RspOperand)
  return target;
}

size_t RspOperand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arithmetic.RspOperand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 num = 1;
  if (this->num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RspOperand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arithmetic.RspOperand)
  GOOGLE_DCHECK_NE(&from, this);
  const RspOperand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RspOperand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arithmetic.RspOperand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arithmetic.RspOperand)
    MergeFrom(*source);
  }
}

void RspOperand::MergeFrom(const RspOperand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arithmetic.RspOperand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num() != 0) {
    set_num(from.num());
  }
}

void RspOperand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arithmetic.RspOperand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RspOperand::CopyFrom(const RspOperand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arithmetic.RspOperand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RspOperand::IsInitialized() const {
  return true;
}

void RspOperand::Swap(RspOperand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RspOperand::InternalSwap(RspOperand* other) {
  using std::swap;
  swap(num_, other->num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RspOperand::GetMetadata() const {
  protobuf_arithmetic_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_arithmetic_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Arithmetic
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Arithmetic::ReqOperand* Arena::CreateMaybeMessage< ::Arithmetic::ReqOperand >(Arena* arena) {
  return Arena::CreateInternal< ::Arithmetic::ReqOperand >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Arithmetic::RspOperand* Arena::CreateMaybeMessage< ::Arithmetic::RspOperand >(Arena* arena) {
  return Arena::CreateInternal< ::Arithmetic::RspOperand >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
